### ISSUE TITLE
Language select not responsive

### ISSUE THREAD

**Issue by jld3103** [electricitymap/electricitymap-contrib#1841]
The language select should be display full screen on mobile devices.

**Comment by corradio** [comment]
Also, in the mobile *app*, the redirect needs to be different, see
https://github.com/tmrowco/electricitymap-contrib/blob/master/mobileapp/www/index.html#L11

**Comment by oscarmrom** [comment]
Hello! Initial contributor here. 

I started to take a look at this and give it a shot. At very minimum this is a rough draft of what it could look like. 

![image](https://user-images.githubusercontent.com/26697231/136024954-ad09c5fe-4aae-423d-8c09-0ba0740f4a3e.png)

Due to the way the toggle works based on the button I made the `Select Language` button have a larger z-index than the `language-select-container` so you can still toggle it off if you wanted to without clicking on a language and forcing a refresh. 

I added a media query to the `#language-select-container` of `max-width:700px;`.

What do people think?

**Comment by jld3103** [comment]
To me the toggle button looks somewhat random placed (although it's not). I'd opt for an X at the top right corner to close it. Otherwise it looks good to me.

**Comment by Kongkille** [comment]
In connection with historical view we are looking a bit further into this as well
