### ISSUE TITLE
Historic Data Available for Turkey

### ISSUE THREAD

**Issue by tarnh** [electricitymap/electricitymap-contrib#2100]
The total solar capacity of Turkey is 5 GW (end of 2018).

Even on a gray day German solar generates a few percent of it's total installed capacity. According to electricitymap Turkish solar produces only 0-1 % of it's installed capacity on most days. Additionally they still use an outdated capacity of 3.5 GW.

These low production values are very unplausible! Do you have any explanation for this?

**Comment by alixunderplatz** [comment]
Hi @tarnh. thank you for pointing at this issue. We are aware of this issue, but there is no way to fix this in the live map, because to my knowledge, only a tiny part of generation from solar is published at the moment. The reported solar seems to come from some "licensed" pv plants or from older plants only. There is a website with market data, which is published a few days later. there you can clearly see that there is a larger part of solar generation missing.
Check the issue #1312 for my comments from 9th April 2018 on this.
I wish we could display the entire solar production data of TR in real-time.
btw: are you from Turkey? if so, could you reach out to the data publishers?

**Comment by alixunderplatz** [comment]
This is what I calculated for the historical data for October 2019 (later data not yet available):

![image](https://user-images.githubusercontent.com/25743609/69481350-e3108e00-0e10-11ea-9d81-16d6196e9c0b.png)
There is a significant amount of solar missing - up to 4.7 GW at peak times.
As I said before, we can do nothing about the data for the real-time map. Except for asking the data providers for their help.
However, we could add a feature to the parser to fetch the historical data to get corrected/completed solar values.
This page has the historical data:
https://seffaflik.epias.com.tr/transparency/uretim/gerceklesen-uretim/uevm.xhtml
"Diğer" or "Other" on top of the diagramm in the lower half of the page is the "solar" category.
It's not included in the data table or the excel file, so we'd have to calculate 
"TOTAL" - (sum of all "production types") to get "solar". Or we take it from the graph / API / query / ... 
@corradio Do you want the historical data for Turkey to be fetched for the database?

**Comment by corradio** [comment]
@alixunderplatz yes indeed that would be terrific! Then we can correct historical data if there are issues.

**Comment by Kongkille** [comment]
It seems that the solar numbers are much more realistic now. 

![image](https://user-images.githubusercontent.com/45588799/165734384-fb4ab83e-1193-42a5-853a-a08cfebb1a38.png)

If someone thinks there's still a discrepancy, please feel free to reopen the issue :)
