### ISSUE TITLE
Tropical hydropower plants have far higher CO2-equivalent emissions compared to the IPCC 2014 data

### ISSUE THREAD

**Issue by RRyyas** [electricitymap/electricitymap-contrib#2484]
Hydropower plants located in northern Brazil and other tropical regions should have far higher carbon emissions data because the flooded reservoirs themselves emit methane gas, and should be taken into account for the carbon intensity in the region. According to the IPCC 2014 data, the median lifecycle emissions (the one that's used) is at 24 gCO2e/kWh, and the maximum lifecycle emissions is somewhere at 2200gCO2e/kWh, where most (if not all) tropical hydropower plants occupy the last 25th percentile of 225+gCO2e/kWh. Dams located in subarctic and arctic climates have the lowest emissions at below 15gCO2e/kWh, according to [https://www.sciencedirect.com/science/article/abs/pii/S0301421596001255](url)

**Comment by robertahunt** [comment]
Good points @RRyyas. Since I am not so familiar with this topic, if you have time to dig deeper, could you make some specific suggestions as to the zones this affects (is it just northern brazil, or all of  is it most of south america?) and what exactly you think the values should be? Then someone in the community (or you) can make a pull request updating the zone overrides for our co2 parameters (https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json).

**Comment by VIKTORVAV99** [comment]
I just read the abstract of the PDF and it mentions the lower co2eq (15 g co2eq) in cold climates, the question is if this should apply to Canada, Sweden, Norway, Finland and Iceland? 

I sadly don't have access to the full pdf so I would greatly appreciate if someone else could look into this.

**Comment by RRyyas** [comment]
Well i don't know exactly how to implement this, because it would require looking at the environmental impacts of each hydropower plant out there. Unless there is average estimates of the CO2 emissions for hydropower plants in each climate zone, it's going to be quite difficult. It can vary from up to 8500gCO2e/kWh for the Balbina Dam down to just 5.5gCO2e/kWh for a typical "run-of-the-river" hydro plant, according to Azad, A., Rasul, M. and Sharma, S., 2016. Clean Energy For Sustainable Development. Elsevier Science, p.58-61.

**Comment by VIKTORVAV99** [comment]
From the abstract and the original issue comment it looks to be broken down into a few regions but I don't know how detailed that breakdown is.

If it is sub artic and artic is one region then (all of?) Swedens hydro power should have a 15g co2eq/kWh since almost all is dams and are located in the sub artic.

The biggest issue I can see right now is when a lot of hydro plants is located just outside the sub artic region and some inside. For example Southern Norway would have a much higer carbon intensity than Northern Norway.

**Comment by alixunderplatz** [comment]
@RRyyas @VIKTORVAV99 the described carbon intensity issues are relavant for "hydro dam+reservoir" type powerplants, since they occupy a large are with their reservoirs. Of course these are the most powerful ones with the highest outputs, but you could also have a bunch of run-of-river type plants elsewhere, that don't occupy a big surface because they are integrated into the existing rivers. Both types go into the usual "hydro" category, and that's where it gets hard to distinguish their influence.
From what I remember, we used to have something like 2g/kWh for Norwegian hydro from another study. If you search in the history of issues for "Norway hydro" you might find it somewhere here.
For the tropical regions: wouldn't you cut at least the trees before flooding? I think that's at least what's done today to reduce methane for new projects. Or do the methane emissions come from biomass that's accumulating on the grounds of the reservoirs? 
I feel like there is no real solution for this issue except for leaving intensity on the IPCC level as the most generic assumption.

**Comment by VIKTORVAV99** [comment]
@alixunderplatz I have been trying to look into alternative sources for co2eq for hydro power. I found this news article: https://www.hydropower.org/news/study-shows-hydropower%E2%80%99s-carbon-footprint 
Witch seem to place the median co2eq at 18.5g co2eq/kWh but I haven't locked into the report it's based on yet.
Obviously this need to be verified but perhaps it could potentially be a new default value for hydro?

**Comment by RRyyas** [comment]
@alixunderplatz The emissions from the tropical dams are caused by the flooding of the rainforest, that has alot of trees and the ground is rich on decomposed carbon. When it's flooded, the bacteria starts to decompose it faster, turning it into methane gas, that is a much potent greenhouse gas compared to carbon dioxide.  Also, note that "median emissions" isn't the same as average emissions. According to https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0161947, the average is much higher than the median, with 273gCO2e/kWh, because those tropical dams, especially in the Amazon rainforest, bump the emissions up far above the median carbon intensity by several orders of magnitude. The hydropower plants that emit about as much as the median carbon intensity are typically located in temperate climates where there's not as much carbon reserves in the ground. And of course, the lowest emitting hydropower plants are located in Norway, because they are typically run-of-the-river plants with rocky terrain.

**Comment by Gazer75** [comment]
Actually most of the hydro power in Norway is from reservoir based plants, but most big artificial reservoirs are placed high in the mountains with little vegetation. Most low lying lakes have had very little max elevation change when used for hydro power.

Stats I could find are 2152 reservoirs with 1718 power plants. Total dams including run-of-the-river is 4121.

**Comment by veqtrus** [comment]
I looked at the full text of "Greenhouse gas emissions from hydropower: The state of research in 1996" and "Clean Energy For Sustainable Development" and they both only have data for specific plants.

**Comment by madsnedergaard** [comment]
Thanks for all the info here, we will revisit this when looking at https://github.com/electricitymap/electricitymap-contrib/issues/738 :)
