### ISSUE TITLE
Calculate static carbon intensity for Luxembourg 

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#2632]
The Luxembourg real-time generation mix isn't available because it is combined with that of Germany in ENTSOE. Because Luxembourg sometimes exports to other countries (e.g. Belgium), it would be nice to have a static carbon intensity available.

The generation mix by year is available through the [IEA](https://www.iea.org/countries/luxembourg "Make sure to select 'Electricity generation by source'"), and imports/exports data is available [through public.lu](https://statistiques.public.lu/stat/TableViewer/tableView.aspx?ReportId=12767&IF_Language=eng&MainTheme=1&FldrName=4&RFPath=54).

Coupled with the static carbon intensity of Germany, France and Belgium in ElectricityMap it should be possible to derive the carbon intensity of the Luxembourg grid.

(The [public.lu page](https://statistiques.public.lu/stat/ReportFolders/ReportFolder.aspx?IF_Language=eng&MainTheme=1&FldrName=4&RFPath=54) where I found aforementioned data also has a link to [this table with "National mix of electricity provided to the end-users (in %) 2009 - 2017"](https://statistiques.public.lu/stat/TableViewer/tableViewHTML.aspx?ReportId=12768&IF_Language=eng&MainTheme=1&FldrName=4&RFPath=54))

**Comment by Kongkille** [comment]
That could be a solution,

Just so I understand correctly, the purpose would not be to derive the live CI for LUX but instead a static value that can be used to calculate the LUX exports and thereby its effect on the target country?

**Comment by q--** [comment]
That's right.

An alternative might be, since Luxembourg generation is reported together with that of Germany, to use the German real-time carbon intensity when calculating the impact of imports from Luxembourg to Belgium

**Comment by corradio** [comment]
@q-- feel free to submit a PR! Should be quite fast to fix.

**Comment by q--** [comment]
I cannot find when this happened, but apparently Luxembourgh is now on the map with its own generation data, so this proposal is no longer necessary.

**Comment by fconrotte** [comment]
Can we reopen this issue ? The Luxembourg is not available anymore since a long time but I don't know why

**Comment by Kongkille** [comment]
Looking at ENTSOE it seems the data has become spotty since July 23rd (see [here](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=22.07.2022+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=22.07.2022+00:00|CET|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!CTY|10YLU-CEGEDEL-NQ&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)))

I think before calculating a static value, it might make sense to reach out to ENTSO-E first and see if they have any additional information :)

**Comment by fconrotte** [comment]
Thanks for the tip, I've sent them an email
