### ISSUE TITLE
Update config for zones with delayed data.

### ISSUE THREAD

**Issue by FelixDQ** [electricitymap/electricitymap-contrib#2783]
@masquel recently implemented the ability to configure zones that have delayed data to display a different message.
before:
![image](https://user-images.githubusercontent.com/12124251/97690975-079fcc00-1a9e-11eb-96fc-a7c6dbff2ef5.png)
after:
![image](https://user-images.githubusercontent.com/12124251/97690926-f656bf80-1a9d-11eb-9147-db2e796ca254.png)

To display this message for all zones with delayed data, then we need to update the zones.json with options like this:
```js
{
 ...
  "delays": {
          "production": 24 // up to 24 hours delay
          ...   
  }
}
```

I would appreciate it if someone can help me create a list of zones that have a **expected** delay. Currently, I have the following:
- [ ] EIA zones - 30 hours
- [ ] Greece - 4 hours

**Comment by PaulCornelissen** [comment]
Greece has 4-5hrs of delay.

**Comment by Kongkille** [comment]
Since there hasn't been much activity on this issue, I am closing this.

We have the functionality of inputting expected delays and I have also added a small section on https://github.com/electricitymap/electricitymap-contrib/wiki/Technical-requirements-for-parser-data such that we remember to keep it updated :)
