### ISSUE TITLE
[XK] Get "more realtime" data in Kosovo 🇽🇰

### ISSUE THREAD

**Issue by Manu1400** [electricitymap/electricitymap-contrib#3269]
### source

GET https://www.kostt.com/Content/ViewFiles/Transparency/LoadForecast/Realizimi%20ditor.xlsx "live" production

(found on page https://www.kostt.com/Transparency/LoadForecast )

### compare
* last value : 02/08/2021 06:00:00 => delay: 16 hours (example)

[to remplace daily source](https://www.kostt.com/Content/ViewFiles/Transparency/BasicMarketDataOnGeneration/Prodhimi%20aktual%20gjenerimi%20faktik%20i%20energjise%20elektrike.xlsx)

**Comment by brandongalbraith** [comment]
Crushing it @Manu1400, love all the contributions 💪  ⚡

**Comment by madsnedergaard** [comment]
Seeing as the current version of the parser is very unstable (the document hasn't been updated for 8 days now), I think it would make sense to switch to the new document. Since it doesn't give any breakdown, we should verify if it still only reports for coal plants (maybe compare data with the previous data if possible) or if we should add it all to `unknown` :)

**Comment by vignesh-ponraj** [comment]
Overall, I can understand the parser needs fixing, what I couldn't was the part you mentioned about comparing new and old.

> we should verify if it still only reports for coal plants (maybe compare data with the previous data if possible) or alternatively we should add it all to unknown

So, specifically

- How do I compare the newly identified source with previous data?
- Is the old data the one in the parser currently? or you were referring to [this page](https://www.wikizero.com/en/Electrical_energy_in_Kosovo)?

**Comment by madsnedergaard** [comment]
> * How do I compare the newly identified source with previous data?

I was thinking we could compare the two data sheets, but I see now that there's no historical data and therefore it's pretty difficult.

> * Is the old data the one in the parser currently? or you were referring to [this page](https://www.wikizero.com/en/Electrical_energy_in_Kosovo)?

I was referring to this (the one used in the parser):

https://github.com/tmrowco/electricitymap-contrib/blob/1c63a741ee58e02c905a4db35f76c0c41a2eb782/parsers/XK.py#L23

---

On second thought I think we should switch to the new data sheet.
And if we on the website can find proof that the reported generation is only for coal, then the value should report as "coal" - otherwise as "unknown".

Hope that makes sense :)

**Comment by vignesh-ponraj** [comment]
Thanks Mads! That makes it incredibly clear :) I'll start working on it right away.

**Comment by veqtrus** [comment]
Hi @vignesh-ponraj, I made the original parser. Feel free to ping me if you have any questions.

**Comment by vignesh-ponraj** [comment]
I'm finally done with the changes. Took me a long while since I had to go back to mentor several times, but it helped me really understand the nitty-gritties of existing code. Thanks for your patience team.

I may have to refactor my code a bit before creating the PR.

**Comment by vignesh-ponraj** [comment]
My apologies for not noticing @alixunderplatz's mention of another solution. Though I have a PR I think as @veqtrus suggested it is better to discard it and go ahead with the solution specified in #3408.

Would it be fine if I try my hand at it? @madsnedergaard

**Comment by skovhus** [comment]
That would be great @vignesh-ponraj 🙌

**Comment by KabelWlan** [comment]
This has been fixed in#3792 and therefore it can be closed.

**Comment by madsnedergaard** [comment]
Thanks for the cleaning up @KabelWlan 🙌
