### ISSUE TITLE
frontend: optimize contributors avatars size

### ISSUE THREAD

**Issue by Manu1400** [electricitymap/electricitymap-contrib#3300]
In webpage of a zone [zone](https://www.electricitymap.org/zone/FR) in ElectricityMap, my browser download contributors avatar with two HTTP requests by contributor:

ie: https://github.com/lorrieq.png => Status Code: 302 => https://avatars.githubusercontent.com/u/6525086?v=4 => avatar in large size

### proposal
get avatar from avatars.githubusercontent.com (to avoid redirection) and then use `?s=20` param (for size 20x20)

=> https://avatars.githubusercontent.com/u/28250254?s=60&v=4

**Comment by madsnedergaard** [comment]
That would require knowing the user id of contributors instead of their handle, right? I think that makes it too complicated, but the size paramter is a good point - feel free to update the url here: https://github.com/tmrowco/electricitymap-contrib/blob/master/web/src/components/contributorlist.js

Maybe use `s=40` to ensure we have a retina-friendly size :)

**Comment by Manu1400** [comment]
I assign myself this dev task

URL: https://avatars.githubusercontent.com/lorrieq?s=40 ✔️

**Comment by gwpicard** [comment]
@Manu1400 How is this going? 😄
