### ISSUE TITLE
Portugal data is offset from Spain

### ISSUE THREAD

**Issue by sandos** [electricitymap/electricitymap-contrib#3585]
Comparing Portugal and Spain it is sadly clear that one of them is very off from the other, unless the sun is 6 hours or so offset between them:

Spain:
![image](https://user-images.githubusercontent.com/60831/144793664-bf320ef1-d14e-4cd6-8c12-3c242ed4ae0a.png)
Portugal:
![image](https://user-images.githubusercontent.com/60831/144793699-ab92f73b-1b51-46e2-ad08-63d1681af89c.png)

I assume this is just an issue with a lot of data sources that is hard to fix. Or is this some sort of solar-with-storage?

**Comment by IV1T3** [comment]
Hey @sandos! I have been following the Portugal and Spain data for the last few days now. The data seems to be consistent again, since I couldn't notice any offset in the solar data. 

Since the real-time electricity data sources for both Portugal and Spain is ENTSOE, it might just have been an inconsistency in the data of their Transparency API.

Did you notice this again, since you opened this issue?

**Comment by KabelWlan** [comment]
The issue still seems to be here. Also the hydro generation seems a bit "jumpy" to me.
![Unbenannt](https://user-images.githubusercontent.com/49598085/147333236-fedab0e3-16bb-4fc8-8538-89e8b0a47fad.png)

**Comment by alixunderplatz** [comment]
This is still a thing... Could someone of the electricityMap-team ping ENTSOE to have a look at the timestamps, please? :)
![image](https://user-images.githubusercontent.com/25743609/151797906-5174a29d-0c3b-4dfe-9f6c-823a10ccd17b.png)

**Comment by KabelWlan** [comment]
This seems to be solved. The last few days the solar data is reported at the correct time of the day and the "jumpyness" is gone as well.

**Comment by madsnedergaard** [comment]
Great, let's close this and then reopen if it happens again :)
