### ISSUE TITLE
Can we use SwissGrid to have realtime live data? 

### ISSUE THREAD

**Issue by RSickenberg** [electricitymap/electricitymap-contrib#3654]
Hello,

I found out there is miss-sync data between what SwissGrid is reporting and the map.
Here a look:
![image](https://user-images.githubusercontent.com/16922548/148781620-ff861bf8-89d4-48fc-b0b3-443b73cb3a43.png)
_Source: https://www.swissgrid.ch/fr/home/operation/grid-data/current-data.html_

Maybe you could use this source to fetch the data? 

Thanks for what you did!
Regards

**Comment by Kongkille** [comment]
Thanks for the link. Our current data source for Switzerland is a combination of multiple sources, as there were afaik some issues with the Swissgrid data.


The current solution was made alongside the Swiss Federal Office, so I think that's where the discrepancy is coming from :)

You can see the issue here #2898
