### ISSUE TITLE
App map doesn't show USA data

### ISSUE THREAD

**Issue by margonzalezfranco** [electricitymap/electricitymap-contrib#3693]
Not sure if this is a known issue but I can see the USA data well on the website but not on the app (I am on iPhone). If you need screen shots or other things to help debug reach out: margonzalezfranco@gmail.com

**Comment by brandongalbraith** [comment]
Hi @margonzalezfranco! The territory data availability delta between web and mobile is due to a new "estimates" feature recently pushed to production on the web, but not yet available in the mobile app. 

More context is available at https://github.com/electricitymap/electricitymap-contrib/pull/3664 and https://github.com/electricitymap/electricitymap-contrib/pull/3667.

**Comment by 0thomas** [comment]
@madsnedergaard Can be closed, thanks for estimations in the App ;)
