### ISSUE TITLE
Wind Data for Austria missing from ENTSO-E

### ISSUE THREAD

**Issue by maxp1256** [electricitymap/electricitymap-contrib#3720]
Currently the wind energy data for Austria is wrong. It was very windy total, but the app Shows online 4 MW / 0.11%
Entsoe is showing > 1 GW

**Comment by jarek** [comment]
`BZN|AT` is showing 4 MW for onshore wind for me as well for all of 28.01.2022, so the problem seems to lie somewhere before data submission to ENTSO-E

https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=28.01.2022+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=28.01.2022+00:00|CET|DAYTIMERANGE&area.values=CTY|10YAT-APG------L!BZN|10YAT-APG------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2) 

![Screenshot 2022-01-28 at 21-05-16 Data View](https://user-images.githubusercontent.com/47415/151643158-e8fbc4fb-b5bd-4427-856c-75622b4a9113.png)

**Comment by alixunderplatz** [comment]
![image](https://user-images.githubusercontent.com/25743609/151796762-1fd5f3d3-8908-4cb4-8563-ea08fa9c6434.png)

Looks like a temporary data issue which happens from time to time. For the moment it looks good, so I am closing.
