### ISSUE TITLE
Data for Germany / DE is delayed

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymap/electricitymap-contrib#3732]
During the last week the German data was marked as "delayed", although it is <2h close to real-time on ENTSOE transparency. As a consequence, no export or import arrows with DE are shown on the live electricityMap.

My guess: the few wind energy data points ahead of time could be the cause of it:
![grafik](https://user-images.githubusercontent.com/25743609/152527593-de184558-8d6f-49ae-8f42-fb0dcb309afc.png)

![grafik](https://user-images.githubusercontent.com/25743609/152527875-2024f523-4ad8-4d26-9701-1f8a6b657a31.png)

@madsnedergaard Can you check / fix before the weekend starts? (... we have another very windy weekend incoming ;D)

**Comment by w-flo** [comment]
In your ENTSO-E screenshot, lots of production types are missing. The total generation is only ~13 GW which is less than the 20 GW minimum expected for electricitymap to consider the data as "[valid](https://github.com/electricitymap/electricitymap-contrib/blob/master/parsers/ENTSOE.py#L314)". Seems like lignite, gas, hard coal, pumped hydro, nuclear, solar and onshore wind show as "N/A" today at [ENTSO-E](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=05.02.2022+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=05.02.2022+00:00|CET|DAYTIMERANGE&area.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) (I hope that link works).

So there's some problem with incomplete ENTSO-E data, apparently.

**Comment by madsnedergaard** [comment]
Yeah, something is clearly going on with ENTSO-E's data for Germany these days... I have no idea what, but here's a clear example of the difference in data - the parser will drop things if there's no coal (like on the 2nd screenshot) and that's why it's being estimated.

<img width="981" alt="Screenshot 2022-02-07 at 07 18 53" src="https://user-images.githubusercontent.com/3296643/152734832-003084d2-26dc-486c-bfe2-e64ad42f9b2e.png">

**Comment by w-flo** [comment]
Checking out the ENTSO-E "[Control Area](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTA&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=06.02.2022+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=06.02.2022+00:00|CET|DAYTIMERANGE&area.values=CTY|10Y1001A1001A83F!CTA|10YDE-RWENET---I&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))" tab, it appears that the problem is with Amprion's data. All other German TSOs report valid data.

Maybe issues started after their reporting software update during the [January 27 maintenance](https://transparency.entsoe.eu/news/widget?id=61ea8a54536ba90be732b3b1).

**Comment by madsnedergaard** [comment]
Got the following response from ENTSO-E:
> We are aware of publication delays for aggregated generation per type in Germany and contacted the data provider. I will come back to you when I have an answer. 

So let's hope it'll be fixed soon :)

**Comment by FinnHuelsbusch** [comment]
Seems to be fixed. At least the last 24 hours are availabel.
