### ISSUE TITLE
German electricityMap  not available

### ISSUE THREAD

**Issue by KApel01** [electricitymap/electricitymap-contrib#3767]
Hallo! Since last week German energy data are not available. What happened? Regards!

**Comment by w-flo** [comment]
See #3732 - apparently there are some Amprion data reporting issues with the ENTSO-E transparency platform. Hopefully they can fix it soon. It's not an issue with electricitymap itself (although it might be possible to fetch the data from other sources instead of ENTSO-E, but that would be a lot of work).
