### ISSUE TITLE
Data for Netherlands is missing

### ISSUE THREAD

**Issue by fvanson** [electricitymap/electricitymap-contrib#3802]
Data for the Netherlands is missing, as well as a color in the map.

**Comment by madsnedergaard** [comment]
Hey @fvanson, Netherlands is currently missing on the Android app (I'm actively working on getting a new release out), while we on the web app (and after last night also on iOS) have estimated data for Netherlands.
See a much more detailed explanation of the problem here: https://github.com/electricitymap/electricitymap-contrib/issues/3015#issuecomment-888154930

Therefore we use ENTSO-E data for some of the production types and use [our estimation models](https://github.com/electricityMap/electricitymap-contrib/wiki/Estimation-methods) for the rest :)
