### ISSUE TITLE
"Estimated" note under energy sources can cause flickering

### ISSUE THREAD

**Issue by jarek** [electricitymap/electricitymap-contrib#3807]
1. Go to a zone that has estimated data right now and real data in recent past. We're looking for the "Some data for this region is estimated. Read more about our estimation methodology here." info box.
2. Hover over the 24-hours chart below the fuel source list
3. If you do it right, the display will keep on flickering between most recent data (with "estimated" box) and past data (without  "estimated" box) because the "estimated" box pushes the 24-hours charts down, which makes the chart gain focus, which makes the data shown to set to past when we hove over a past hour, which makes the "estimated" box disappear, which makes the chart lose focus again, which makes the data reset to current, which makes the "estimated" box appear again, and so on.

I've tried to record this happening and attached at the end of the report, hopefully it works.

Browser: Firefox 97.0 on Linux.

![est](https://user-images.githubusercontent.com/47415/154705624-849d7f6a-1761-4dc2-bbe1-e11bb9871a1f.png)

https://user-images.githubusercontent.com/47415/154705256-03f6829e-e352-4eab-a9bb-e73554b5f504.mp4

**Comment by atjohans** [comment]
The cause seems to have been when switching between hovering over data that is estimated, and data that is not estimated. Estimated data caused the new div to appear with the "Some of the data for this region is estimated..." message. which caused everything to shift downward, making it no longer hovered-over, which caused it to move back up which created an endless cycle causing the flickering.

I have a simple solution in place that simply creates a blank "buffer" region that prevents everything from moving when hovering over estimated data. This fixes the flickering.

I could also envision a solution where the system checks if any of the data for the country is estimated and just displays the message if any of the data is estimated, and doesn't display the message if none of the data is estimated.
I am wondering if there is a preferred solution to this issue? (edited) 




Original issue: 

https://user-images.githubusercontent.com/70723718/164061751-4d0539d0-a2be-4370-a5f0-71e63430382b.mp4


The current solution: 



https://user-images.githubusercontent.com/70723718/164061778-04b8b829-1873-435c-90a9-f5448c82bc3d.mp4





I am currently partial to the "buffer" solution, as I have some experience with web dev, and in my experience users tend to prefer when things in the window move around as little as possible

**Comment by madsnedergaard** [comment]
cc @rasmusjeppsen, what are your thoughts on this? And will it still be an issue with historical view? :)

**Comment by VIKTORVAV99** [comment]
@rasmusjeppsen I think we could remove the white space even when countries have estimated data. By moving the data source element on the bottom to where the estimated box currently is and making it expandable we should show it permanently.

When from a parser:
Show a small box that says parser and if expanded shows the full URL to the data source.

When the data is estimated:
Shows estimated in the box and when expanded explains what it means. (current information)

**Comment by rasmusjeppsen** [comment]
@VIKTORVAV99 Thank you for the suggestion! I think that moving the data source element to the bottom is a good fix for the bug which will also avoid the need of adding extra white spacing.

I believe it is fine that we show the full information when the data is estimated without adding an 'expand' interaction to the box, as the box will only be displayed once something is estimated and will be at the bottom of the screen below all the graphs. Also, when the data is from a parser, I don't think we need to display a box for this, as this is the default.

Here is a design mockup of how I think we can move the box: 

<img width="441" alt="estimated-box_bottom" src="https://user-images.githubusercontent.com/58597172/165479905-4bcb1df6-9554-4db7-be51-3e2a8e0e8674.png">

Thank you again for this suggestion, Viktor! This is a great fix and I think we should move forward with the solution of moving the box to the bottom of the screen as you suggest.

**Comment by VIKTORVAV99** [comment]
@rasmusjeppsen I was actually thinking about the opposite. My plan was to move the source string up to where the estimated box was now, hence the need for a expanding box. 😅

But this works too!

I still think we should work on merging the source string and the estimated notice but it's nothing we need to rush. (maybe add a icon or two (switching icon depending on the source type) to make it a little more stylish like the pro labels?)

**Comment by VIKTORVAV99** [comment]
@rasmusjeppsen I could work on this if you want.

If we just move it to the bottom I could have a PR ready tomorrow.

But I have a few more changes in mind I'd like to try out. That's gonna take a little longer but I think you'll like the result.

**Comment by VIKTORVAV99** [comment]
Rough draft when the data is from a API:
Expanded (default):
![image](https://user-images.githubusercontent.com/30777521/167628816-219091fd-61d7-47e9-a7d1-04f2a652eb5c.png)
Collapsed:
![image](https://user-images.githubusercontent.com/30777521/167629712-4647282b-2dc5-42f5-a09f-5be45edd135c.png)


Rough draft of when it's estimated:
Expanded (default):
![image](https://user-images.githubusercontent.com/30777521/167629194-fe142f51-6099-4fc6-a741-d49ec30b7dc2.png)
Collapsed:
![image](https://user-images.githubusercontent.com/30777521/167629462-2daee301-2d1b-49ac-93b5-52e8b6864952.png)

@rasmusjeppsen and @madsnedergaard what do you guys think?


The icons is just placeholders for now until I find more appropriate ones and the same goes for the text but I feel like with this approach we can better explain what a API means vs what estimation means.

Maybe the expanded/collapsed functionality is a bit over the top though?

Do we want to split up API and parser explanation/labels?

**Comment by VIKTORVAV99** [comment]
@jarek what do you think, is this still a problem or can we close the issue?

My pr didn't exactly fix it but midigated almost all of the flickering at least.

**Comment by jarek** [comment]
I think it's now addressed well! I couldn't get it to flicker now, the worst was that it can jump back up after scrolling down when estimated - but it's not a flicker back and forth. So I'll close this - thanks!
