### ISSUE TITLE
Wrong mapping

### ISSUE THREAD

**Issue by comav** [electricitymap/electricitymap-contrib#3830]
The map shows Crimea as russian territory, but it is not![Screenshot_2022-03-06-23-51-50-463_com.android.chrome.jpg](https://user-images.githubusercontent.com/61016697/156943654-21d7ae82-6ed4-4ee5-8daf-c58b563d31f5.jpg)

**Comment by jarek** [comment]
Hello and thank you for your note.

Crimea is shown separate from main part of Ukraine because it is currently a separate electrical grid.

If you tap or click on it, you can see that Crimea is shown separately from Russia and labelled with an Ukrainian flag: https://app.electricitymap.org/zone/UA-CR
