### ISSUE TITLE
Indicate share of renewables in Israel's "unknown"

### ISSUE THREAD

**Issue by Gl4d1u5** [electricitymap/electricitymap-contrib#3858]
I live in Israel and I know for a fact that we have solar farms. The percentage of renewable may be low but not zero.
**source:** https://www.iea.org/countries/israel

**Comment by jarek** [comment]
Looks like currently it's all classified as "unknown" because there is no dynamic breakdown by source, and "unknown" defaults to fossil fuel. For reference, the parser was added in https://github.com/electricitymap/electricitymap-contrib/pull/2124

The carbon intensity value does take some renewables into account: per IEA 2020, we assume a static breakdown of 28.1% coal, 65.3% gas, 0.4% oil, 5.3% solar, 0.3% wind, 0.3% other: https://github.com/electricitymap/electricitymap-contrib/blob/9138529dba29574edccf9147413045e21d71a98b/config/co2eq_parameters_lifecycle.json#L419-L423

I think Electricity Map backend has since made some improvements, so we could try to configure Israel's "unknown" to show up as about 5.6% renewable. Unfortunately given lack of more detailed data, it is a rather imperfect approximation, since it's mostly solar which means renewables are higher during the day and much lower at night.

As another topic, currently we're showing a static load of 15819 MW because that's what the source page indicates (https://www.iec.co.il/en/pages/default.aspx). Per the original PR, this used to change hourly, but unfortunately there doesn't seem to be a timestamp for the data, so we have no way of knowing when it stopped changing.

**Comment by Kongkille** [comment]
For now, we can't show directly in the graphs an hourly VRE production measurement.

We recently launched our estimation feature, which helps us estimate the production mix but it requires us to set up a specific estimation model for Israel to be able to split it out from unknown and we have not yet developed such a model for Israel.

I am, however, wondering whether it makes sense that it says 0 % renewable and 0 % low-carbon when we know it could be part of the unknown mix.

In this case it might be more informative if it was something like this? Similarly to when data is missing

![image](https://user-images.githubusercontent.com/45588799/158574461-a447e2c9-de10-48ad-9d77-0f3d04f56459.png)




CC @rasmusjeppsen

**Comment by pierresegonne** [comment]
Closing as we've now added IL to the list of estimated countries :)

**Comment by rasmusjeppsen** [comment]
> I am, however, wondering whether it makes sense that it says 0 % renewable and 0 % low-carbon when we know it could be part of the unknown mix.

Agreed! I think showing a ? symbol is more accurate than showing 0% in situations like this where we do know that it could be part of the unknown mix and thus 0% is not necessarily accurate.

Also, great that IL is now added to the list of estimated countries :)
