### ISSUE TITLE
Consideration of Electricity Trading

### ISSUE THREAD

**Issue by markus71at** [electricitymap/electricitymap-contrib#4277]
Hi!
I like your app and wanna thank for your great effort. 
Unfortunately it seems you only track physical transport of electricity but not trading.
For example: Our local energy distributor in the Tirol (Austria) states in the yearly report to buy 20% of sold energy in Norway.
It would be great to see the tradet electricity not the physical. 
Regards, Markus

**Comment by jarek** [comment]
This is because Electricity Map shows physical properties of electricity being consumed, to indicate the actual physical climate impact of electricity consumption. If you consume 1 kWh of electricity in Tirol, approximately none of the energy will actually come from Norway. It's not all that bad, since it's mostly Austrian hydroelectricity per https://app.electricitymap.org/zone/AT, but it's not Norwegian.

The smoothie analogy in https://electricitymap.org/blog/flow-tracing/ might be helpful.

This blog post from 2018 https://electricitymap.org/blog/green-electricity-contracts/ might also be an indication that a view based on traded electricity is unlikely to be added on Electricity Map. It includes an example with Norway at the very end.

**Comment by VIKTORVAV99** [comment]
Closing this as not planned.
@markus71at if you got any questions about this please feel free to open a discussion instead as it's a better fit for discussion as this.
