### ISSUE TITLE
Estimate for nuclear in Belgium looks odd

### ISSUE THREAD

**Issue by autipial** [electricitymap/electricitymap-contrib#4323]
The estimate today for nuclear generation in Belgium looks odd, i.e. it gives a much higher estimate than the actual values actually registered during the previous hours.
Even if a variation of the nuclear production is of course possible, it would perhaps make sense to stick with the last actual value registered (only for the specific case of nuclear power) in order to avoid inconsistencies.

![estimate_belgium](https://user-images.githubusercontent.com/7460404/177049110-924574d5-d1da-453b-8658-c11c5f7f76d5.png)

**Comment by VIKTORVAV99** [comment]
Using the last recorded production value would probably work for 90% of the time but I belive using the vector of the last 6 hours to predict the next hours production values with the installed capacity as a upper limit (and 0 as a lower limit) would be a better option.

I believe it would better estimate when nuclear production is ramping up and down.

@pierresegonne what do you think? Could this be implemented for nuclear (and perhaps geothermal) only? We could call it something like "linear prediction estimation" as it would only deal with future values.

It could also be further enhanced by using the unavailability data I suggested in #4185 and https://github.com/electricitymap/electricitymap-contrib/discussions/4219#discussioncomment-2880588 to further refine the upper bounds.

**Comment by pierresegonne** [comment]
Hey thanks for raising this issue.

In this case, the estimate looks odd because the historical level of nuclear power production for BE must have been higher. With our current estimation methodology, we can't really avoid these issues :/

Your suggestion @VIKTORVAV99 is a good one, as we know that nuclear production can't fluctuate freely. The data quality system we're working on will in the near future flag the estimates that are suspicious like this one and will give us a better overview around where to focus our efforts for improving the estimation models :)

**Comment by VIKTORVAV99** [comment]
> Hey thanks for raising this issue.
> 
> In this case, the estimate looks odd because the historical level of nuclear power production for BE must have been higher. With our current estimation methodology, we can't really avoid these issues :/
> 
> Your suggestion @VIKTORVAV99 is a good one, as we know that nuclear production can't fluctuate freely. The data quality system we're working on will in the near future flag the estimates that are suspicious like this one and will give us a better overview around where to focus our efforts for improving the estimation models :)

Now this isn't Belgium but Sweden:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/30777521/179906950-6183d1ff-0a78-4e52-8ec1-933d8a8ec6b1.png">

As you can see the estimation model clearly overestimate the nuclear production but I can't say I blame it, one of the nuclear power plants had a emergency disconnect of 1400 MW and there would be no way of estimating this based on historical data.

However I think my solution would alleviate this problem, clearly the linear prediction would also have failed in the early hours but it would have been offset somewhat by the upper bounds of the unavailability data and now at a later stage the linear prediction would have worked pretty much flawlessly (I think 😅).

Just something to keep in mind when to decide where to focus your efforts, also just the linear prediction shouldn't be too hard, it's the unavailability data that would require parsers and data structures etc, so if you (we) wanted it could be a 2 step implementation, first the linear model and then the unavailability data at a later date (for all models).

**Comment by pmensalt** [comment]
It's not only the nuclear that is off, but it can happen for other types too:

<img alt="image" width="414" src="https://www.imgdumper.nl/uploads9/62d969c8ac879/62d969c8a9853-image_2022-07-21_165922863.png">
--> Here, you can see a massive jump in solar production for the estimated value. The estimation model is using previous values to extimate the current value. But.. the previous days were  very sunny, and the current one isn't. 

Maybe this can be improved by looking at the previous values, and calculate the **average difference** (increase or decrease in percent) instead of the **average value**. 
For example:
Let's say we have the following data:
current day = T
values are enery production for solar energy.

T - 3 at 12:00 = 10, at 13:00 = 13 ==>  30% increase
T - 2 at 12:00 = 15, at 13:00 = 17 ==>  13% increase
T - 1 at 12:00 = 12, at 13:00 = 15 ==>  25% increase

==> average increase from 12:00 to 13:00 of the previous days = 22.7%

current day at 12:00 = 2
Estimation model can now use the average increase to calculate the current estimated value: 2 * 1.227 = **2.45**
Current estimation model seems like to use the average value of the values at 13:00 of the previous days, which would be (13 + 17 + 15) / 3 = **15**.

The difference between those two values is huge, and the first one is probably much closer to the real value then the current estimated value.

This algorithm is perfect to be used for energy sources that do not have the same stable production across days, like renewable energy sources (solar and wind), but might solve the above issue with nucleair energy too: As the production is mostly lineair, the difference percent will mostly be 0%, meaning the estimated value will be the same as the previous value.

For the remaning energy sources, which can easily be scalled up or down to produce the remaining energy needed (on top of nucleair and renewable) like gas, coal, etc: It might be a good idea to calculate the weighted average of total amount of produced energy of the previous days, but also including the same day of the previous week(s) (which should have a higher  weight, because, week days and weekend days typically have a different energy need).
By calculating this weigthed average amount of needed energy, the remaining needed energy can be calculated (by subtracting the calculated values for renewable and nuclear from the total energy need), and distributed across the remaining types of energy sources. To get a good distribution across the different types, the average distribution of the previous days might be used.

**Comment by VIKTORVAV99** [comment]
> but might solve the above issue with nucleair energy too: As the production is mostly lineair, the difference percent will mostly be 0%, meaning the estimated value will be the same as the previous value.

While it's true the difference will mostly be 0% on normal days this is definitely not true when plants enter and exits maintenance periods. That is why I think using a linear model of the last 6 hours with a ceiling of the installed capacity - unavailable production is the best way forward for now.

**Comment by pmensalt** [comment]
For nuclear, it's indeed not necessary to do it as described above, the same value can be used again. I just included it, so the same code/calculation could be reused for nuclear too. 

However, for solar and wind, a better estimation is really needed. Currently, the estimated value for Belgium is way off:

<img width="400" src="https://www.imgdumper.nl/uploads9/62decf3d84e08/62decf3d82053-image_2022-07-25_191333401.png" alt="62decf3d82053-image_2022-07-25_191333401" /> <img width="400" src="https://www.imgdumper.nl/uploads9/62decf5f6e4bb/62decf5f6a262-image_2022-07-25_191407246.png" alt="62decf5f6a262-image_2022-07-25_191407246" />

Previous carbon intensity was 63g, estimated new value is 195g (more than tripple the previous value)! With the algorithm describe above, this value would be much closer to the real value.

And the estimated value includes (a little bit of) coal, which isn't being used in Belgium. The above described method would not include it (because the previous value was 0, and multiplying it with a value will still be 0).

**Comment by VIKTORVAV99** [comment]
> Edit: Should I extract this to a new issue?

Perhaps even a discussion would be a good idea? So many ideas floating around in here.

**Comment by pierresegonne** [comment]
Yes I think it would make sense to move this to a discussion instead of an issue, as it's better suited for general ideas and improvements :)

**Comment by pmensalt** [comment]
> > Edit: Should I extract this to a new issue?
> 
> Perhaps even a discussion would be a good idea? So many ideas floating around in here.

> Yes I think it would make sense to move this to a discussion instead of an issue, as it's better suited for general ideas and improvements :)

I've created a new discussion: https://github.com/electricitymap/electricitymap-contrib/discussions/4383

**Comment by pierresegonne** [comment]
Thansk @pmensalt ! I'll let you then close the issue in the coming days except if something completely different than blaming the models comes up
