### ISSUE TITLE
Please add South Africa

### ISSUE THREAD

**Issue by NicorDesigns** [electricitymap/electricitymap-contrib#4343]
Daily Twitter Reports : https://twitter.com/SikonathiM/status/1546562652159320064

https://twitter.com/Eskom_SA

**Comment by VIKTORVAV99** [comment]
Hi!
Adding South Africa would definitely be a nice addition but in order to do so we need a proper data source that publish hourly or better data.

Do you know if Eskom publish this data?

If Eskom (or someone else) do have this data is it in real time (under 2 hour delay)?

If not then the data would have to be estimated and that would be entirely up to the team and data quality.

**Comment by NicorDesigns** [comment]
Thanks for the response: Maybe this can be helpful: (daily data it seems
not real time)

https://www.eskom.co.za/dataportal/supply-side/
https://www.eskom.co.za/dataportal/ocgt-usage/
https://www.eskom.co.za/dataportal/renewables-performance/

Looks like the data download here
https://www.eskom.co.za/dataportal/supply-side/station-build-up-for-yesterday/
might be useful?

Regards

Nicolaas Kock
Senior Software Engineer
NicorDesigns LLC

**Comment by NicorDesigns** [comment]
https://www.eskom.co.za/dataportal/emissions/
Nicolaas Kock
Senior Software Engineer
NicorDesigns LLC

**Comment by IV1T3** [comment]
We already have an open issue regarding South Africa: #2881.

**Comment by VIKTORVAV99** [comment]
> We already have an open and active issue regarding South Africa: #2881. I suggest closing this issue in favor of #2881 and continuing the discussion there.

Ah I missed that, closing this as a duplicate in favor of #2881 then.

@NicorDesigns please feel free to add any additional information on that issue instead.
