### ISSUE TITLE
Update transmission capacity NO3-NO5

### ISSUE THREAD

**Issue by Gazer75** [electricitymap/electricitymap-contrib#4467]
The NO3 **to** NO5 capacity should be increased to 800MW.
https://umm.nordpoolgroup.com/#/messages/3355b9ad-9ef8-48bf-8743-4b11a1a3b350/1

I've seen values well above the 500MW now used.

**Comment by VIKTORVAV99** [comment]
We use the values on the [Maximum Net Transfer Capacities Map (pdf)](https://www.nordpoolgroup.com/link/d6a149b7ce4f49c1ac342c37d02f30e7.aspx), but since this is a official statement from Statnett (via Nordpool) it should be safe to increase it I suppose.

**Comment by Gazer75** [comment]
The NTC is still 500MW normally, but the actual capacity is higher. It depends on the grid elsewhere how the flows are. Typically the NO3-SE2 that is on a single 420kV line.
It makes no sense that the Høyanger-Sogndal 420kV + Myklebust-Mel 132kV would only have 500MW capacity.
The 420kV and 300kV grid is connected with a 1000MVA auto transformer in Sogndal as well.
https://openinframap.org/#10.46/61.3118/6.5874

**Comment by VIKTORVAV99** [comment]
> The NTC is still 500MW normally, but the actual capacity is higher. It depends on the grid elsewhere how the flows are. Typically the NO3-SE2 that is on a single 420kV line.
> It makes no sense that the Høyanger-Sogndal 420kV + Myklebust-Mel 132kV would only have 500MW capacity.
> The 420kV and 300kV grid is connected with a 1000MVA auto transformer in Sogndal as well.
> https://openinframap.org/#10.46/61.3118/6.5874

That is why we don't use the Net Transfer Capacities but the _**Max**_ Net Transfer Capacity.  But in either case it should be safe to update it, I'll put together a PR later today.

**Comment by Gazer75** [comment]
Problem is the TSOs only publish the NTC value I believe. Basically the capacity available for trade.
I know Statnett is working on a new way to calculate capacities so the trade capacity is more in line with the actual capacity of the lines/cables. Last I read its supposed to come into effect next year.
When that happens I guess the NTC will vary a lot more through the year.

Thanks for fixing though.

**Comment by VIKTORVAV99** [comment]
> Problem is the TSOs only publish the NTC value I believe. Basically the capacity available for trade. I know Statnett is working on a new way to calculate capacities so the trade capacity is more in line with the actual capacity of the lines/cables. Last I read its supposed to come into effect next year. When that happens I guess the NTC will vary a lot more through the year.
> 
> Thanks for fixing though.

Statnett has reported a MAX NTC to ENTSO-E that Nordpool uses, this MAX NTC is the maximum theoretical sustained load. And yes stattnet together with the other nordic TSOs are working on a flow based model that need lower tolerances for operation but the MAX NTC will still be needed and won't vary unless new infrastructure is installed.

I looked through some of the sources I have used in the past regarding transfer capacity and I have seen no mention of the increased capacity but since ENTSO-E is reporting numbers over 500 MW it makes sense to update it, I didn't have time to do it yesterday but I'll do it shortly, just have some other PRs and Issues to handle first.
